name: My EC2 App CI/CD

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: ap-south-1
  ECR_REPOSITORY: my-ec2-app
  AWS_ACCOUNT_ID: "251869519234"

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v5
        with:
          role-to-assume: arn:aws:iam::251869519234:role/GitHubActions-ECR-MyApp-Role
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        run: |
          aws ecr get-login-password \
            --region "$AWS_REGION" | \
          docker login \
            --username AWS \
            --password-stdin \
            "$AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com"

      - name: Build Docker image
        run: |
          docker build \
            -t "$ECR_REPOSITORY:${{ github.sha }}" \
            .

      - name: Tag Docker image
        run: |
          docker tag \
            "$ECR_REPOSITORY:${{ github.sha }}" \
            "$AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPOSITORY:${{ github.sha }}"

      - name: Push Docker image to ECR
        run: |
          docker push \
            "$AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPOSITORY:${{ github.sha }}"

      - name: Deploy to EC2 with SSM
        run: |
          IMAGE_URI="$AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPOSITORY:${{ github.sha }}"

          COMMANDS=$(jq -nc \
            --arg region "$AWS_REGION" \
            --arg registry "$AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com" \
            --arg image "$IMAGE_URI" \
            '[
              "systemctl stop myapp.service || true",
              "systemctl disable myapp.service || true",
              ("aws ecr get-login-password --region " + $region + " | docker login --username AWS --password-stdin " + $registry),
              ("docker pull " + $image),
              "docker rm -f my-ec2-app || true",
              ("docker run -d --name my-ec2-app --restart unless-stopped -p 8080:8080 " + $image),
              \"sleep 5\",
          \"curl -fsS http://127.0.0.1:8080\"
            ]')


          aws ssm wait command-executed \
            --region "$AWS_REGION" \
            --command-id "$COMMAND_ID" \
            --instance-id "i-08e8bec7102526dac"

          aws ssm get-command-invocation \
            --region "$AWS_REGION" \
            --command-id "$COMMAND_ID" \
            --instance-id "i-08e8bec7102526dac" \
            --query '{Status:Status,Output:StandardOutputContent,Error:StandardErrorContent}' \
            --output yaml
